pipeline {
  agent {
    docker {
      image 'gradle:6.6.1-jre14-openj9'
    }
  }

  stages {
    stage('Verify') {
      steps {   
        sh 'ls -l "$WORKSPACE"'                           
      }
    }
   stage('Checkout code') {
      steps {
        echo "Checking out project"
        // GIT checkout
        checkout scm: [
                $class: 'GitSCM',
                branches: [[name: '*/main']], 
                doGenerateSubmoduleConfigurations: false, 
                extensions: [[$class: 'CleanCheckout']], 
                submoduleCfg: [], 
                userRemoteConfigs: [[url: 'https://github.com/monicacrespo/bootcamp-devops-student-jenkins.git']]
        ]
      }
    }
    stage('Compile') {
      steps {
        dir("$WORKSPACE/calculator"){
            echo "Compiling project"
            sh '''
            chmod +x gradlew
            ./gradlew compileJava
            '''
        }    
      }
    }
    stage('Unit Tests') {
      steps {
        dir("$WORKSPACE/calculator"){
          echo "Running unit tests" 
          sh './gradlew test'
        }
      }
    }
  } 
}